### ISSUE TITLE
icepick or seamless-immutable vs. Immutable.js

### ISSUE THREAD

**Issue by dangoor** [petehunt/react-howto#7]
I love the idea of what you're doing here. Be careful it doesn't turn into a book ;)

Immutable.js is a great library, but I think [icepick](https://github.com/aearly/icepick) is a better fit for most projects. The weight is tiny, your objects all remain inspectable in the dev tools, can be seamlessly passed around to other JS libraries and the performance should be acceptable unless you're working with objects/arrays that have a huge number of keys (in which case Immutable.js is the right choice).

**Comment by petehunt** [comment]
Hey! Good hearing from you again.

Icepick seems pretty cool, but I hadn't heard about it before this. My main point of mentioning `immutable.js` was to get people to *not* use it when first starting to use React.

So I'm going to close this issue, not because I won't try (or even recommend!) icepick, but because I don't think it's confused enough people to warrant mentioning it :)

**Comment by dangoor** [comment]
Haha. Yeah, that makes sense. Immutability is awesome, but new React users definitely need to get over the hurdle of having a functional UI before that's even a consideration!
